name: Build and delivery a Gradle project
description: Build and delivery a Gradle project
branding:
  icon: 'rotate-cw'
  color: 'purple'

inputs:
  token: 
    description: 'a token with write access to the repository'
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ -z "${{ inputs.token }}" ]; then
          echo 'No token set'
          exit 1
        fi
    - uses: actions/checkout@v3.5.3
      with:
        token: ${{ inputs.token }}
    - uses: mikefarah/yq@v4.35.2
      id: explode
      with:
        cmd: |
          for target in .github/real-workflows/*; do
            yq 'explode(.) | select(di==1)' "$target" > ".github/workflows/${target/.*\/}"
          done
    - shell: bash
      run: |
        git config --global user.name "GitHub Actions YAML generator [bot]"
        git config --global user.email "yaml.actions.bot@users.noreply.github.com"
        git add .github/workflows/
        git diff --staged --quiet || git commit -m "ci: regenerate workflows"
        git push
