name: Generate workflows

on:
  push:
    branches:
      - master
    paths: 
      - ".github/real-workflows/*.yml"

jobs:
  generate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run locally
        uses: 'DanySK/true-yaml-actions@1.0.5'
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
