name: Generate workflows

on:
  push:
    branches:
      - master

jobs:
  generate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run locally
        uses: 'DanySK/true-yaml-actions@master'
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
